apiVersion: v1
kind: Service
metadata:
  name: book-store-backend-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: book-store-backend
