apiVersion: v1
kind: Service
metadata:
  name: book-store-frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: book-store-frontend
